# Generated by Django 4.1.7 on 2023-11-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('jssid', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
