# Generated by Django 4.1.7 on 2023-11-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='date',
        ),
        migrations.AddField(
            model_name='reservations',
            name='time',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
