# Generated by Django 4.1.7 on 2023-11-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_reservations_date_reservations_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.TimeField(),
        ),
    ]
