# Generated by Django 4.1.7 on 2023-11-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_reservations_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='grade_sec',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.CharField(max_length=15),
        ),
    ]
