# Generated by Django 4.1.7 on 2023-11-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_students_grade_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='location',
            field=models.ImageField(blank=True, null=True, upload_to='locations/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='grade_sec',
            field=models.CharField(max_length=3, verbose_name='Class'),
        ),
    ]
